version: '3.9'

volumes:
  postgres-data:
  mongo-data:
  redis-data:

services:
  postgres:
    image: postgres
    container_name: smartex_backend_postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    # healthcheck:
    #   test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER']
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  redis:
    image: redis
    container_name: smartex_backend_redis
    command: ['redis-server', '--appendonly', 'yes']
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    restart: always

  mongo:
    image: mongo
    container_name: smartex_backend_mongo
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    restart: always

  backend:
    container_name: smartex_backend
    build:
      context: .
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
      - MONGODB_HOST=mongo
      - REDIS_HOST=redis
      - NODE_ENV=production
    ports:
      - 3333:3333
    restart: always
    depends_on:
      - postgres
      - mongo
      - redis
